### ISSUE TITLE
question on tickers and indices tables

### ISSUE THREAD

**Issue by plingit** [camisatx/pySecMaster#26]
Hi. A great work on a system for financial data.  Thank you!
It looks like quandl EOD is not free. Will pySecMaster still be able to extract its data ?

**Comment by camisatx** [comment]
Hey plingit,

Sorry for the delay! Thank you for the kind words. It means a lot.

The Quandl EOD data is a premium service ($70/month, err, looks like the made it $210/quarter...), thus you will have have to pay for that premium subscription before you can have the system download data. If don't pay for the subscription, but still have a Quandl account, you can only get access to the 29 free samples they provide [here](https://www.quandl.com/data/EOD-End-of-Day-US-Stock-Prices) (e.g. AAPL, V, KO, DE, GS).

If you run the system requesting EOD data and don't subscribe to the EOD data, the system will try all ~10k symbols, but will fail at downloading all but those 29 samples. I would not suggest doing this, however, if you really want those 29 samples to be downloaded, I would add a simple `if` statement in the Quandl Extractor class that only extracts those 29 symbols when running the EOD extractor (and not the WIKI extractor), bypassing all other symbols.

Does this make sense?
